In [2]:
from assess_property.read_data import ReadAllYears
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [3]:
yrs = [2015]
vnames = ["PID", "YR_REMODEL", "YR_BUILT", "LIVING_AREA", "LU", "ZIPCODE", "TOTAL_VALUE","YEAR"]
reader = ReadAllYears(yrs, vnames)
reader.read_all_years()
df = reader.df

100%|██████████| 1/1 [00:01<00:00,  1.23s/it]

In [7]:
df.sort_values(by="YR_BUILT", ascending=False).head(10)

               PID  YR_BUILT  LIVING_AREA  LU ZIPCODE  TOTAL_VALUE  YEAR
139538  1804383000  324561.0      39864.0   C   02136      2400927  2015
139537  1804383000  324561.0       5321.0   C   02136      2400927  2015
63382   0304650010   17840.0          0.0  CC   02110      3330000  2015
63383   0304650005    7950.0          0.0  CC   02110      1930000  2015
34939   0601212010    3802.0      14485.0   A   02127      1977600  2015
64374   0304304102    2829.0          0.0  CC   02111       610500  2015
7757    1102733000    2014.0       4440.0  R3   02130       280500  2015
10332   1100871010    2014.0          0.0  CM   02119            0  2015
10331   1100871012    2014.0          1.0  RC   02119      1876000  2015
10330   1100871014    2014.0          1.0  RC   02119       634000  2015